#!/usr/bin/env bash

## Define Variables
PROJECTNAME=$1
PROJECTPATH="."

## Define Functions
function run () {
    # Make project directory
    if [[ -d ${PROJECTPATH/$PROJECTNAME } ]]; then
        echo "Project already exists"
        quit
    fi

    mkdir ${PROJECTNAME}

    # cd into it
    cd ${PROJECTNAME}

    # composer require jigsaw
    if  command_exists composer; then
        composer require tightenco/jigsaw
    fi

    # Initialize new Jigsaw project
    if command_exists ./vendor/bin/jigsaw; then
        ./vendor/bin/jigsaw init
    fi

    # Run yarn
    # TODO: add fallback to npm
    if command_exists yarn; then
        yarn
    fi

    # Build site
    if command_exists gulp; then
        gulp
    fi

    # Init Git and make first commit
    if command_exists git; then
        git init
        git add .
        git commit -m 'initial commit'
    fi

    # Open Editor
    if command_exists subl; then
        subl .
    fi
}

function command_exists () {
    command=$1

    if ! hash ${command} 2> /dev/null; then
        echo "Command ${command} not found"
        quit
    fi
}

function quit () {
    trap : 0
    exit 0
}

## Run the script
run
